const RESOURCE_CATALOG = [
  {
    key: "cs50",
    title: "CS50x",
    provider: "Harvard",
    url: "https://cs50.harvard.edu/x/",
    trackKeys: ["software_engineering", "web_product", "ai_ml", "data_analytics"],
    tags: ["foundations", "computer_science", "projects"],
    resourceType: "course",
    providerType: "course",
    level: "beginner",
    weight: 8,
  },
  {
    key: "roadmap",
    title: "roadmap.sh",
    provider: "roadmap.sh",
    url: "https://roadmap.sh/",
    trackKeys: ["software_engineering", "web_product", "cybersecurity_networking", "ai_ml", "data_analytics", "hardware_embedded"],
    tags: ["foundations", "career_roadmap", "documentation"],
    resourceType: "roadmap",
    providerType: "docs",
    level: "beginner",
    weight: 7,
  },
  {
    key: "leetcode",
    title: "LeetCode",
    provider: "LeetCode",
    url: "https://leetcode.com/",
    trackKeys: ["software_engineering"],
    tags: ["practice", "interview", "coding"],
    resourceType: "practice",
    providerType: "practice",
    level: "intermediate",
    weight: 10,
  },
  {
    key: "mdn",
    title: "MDN Web Docs",
    provider: "MDN",
    url: "https://developer.mozilla.org/",
    trackKeys: ["web_product", "software_engineering"],
    tags: ["documentation", "web", "frontend"],
    resourceType: "documentation",
    providerType: "docs",
    level: "beginner",
    weight: 10,
  },
  {
    key: "freecodecamp",
    title: "freeCodeCamp",
    provider: "freeCodeCamp",
    url: "https://www.freecodecamp.org/learn/",
    trackKeys: ["software_engineering", "web_product"],
    tags: ["web", "foundations", "practice", "projects"],
    resourceType: "course",
    providerType: "course",
    level: "beginner",
    weight: 9,
  },
  {
    key: "postman",
    title: "Postman API Fundamentals",
    provider: "Postman",
    url: "https://academy.postman.com/",
    trackKeys: ["software_engineering", "web_product"],
    tags: ["backend", "tooling", "documentation", "api"],
    resourceType: "documentation",
    providerType: "docs",
    level: "beginner",
    weight: 7,
  },
  {
    key: "kaggle",
    title: "Kaggle Learn",
    provider: "Kaggle",
    url: "https://www.kaggle.com/learn",
    trackKeys: ["ai_ml", "data_analytics", "bio_life_sciences"],
    tags: ["ml", "data", "projects", "practice"],
    resourceType: "course",
    providerType: "practice",
    level: "beginner",
    weight: 10,
  },
  {
    key: "huggingface",
    title: "Hugging Face Learn",
    provider: "Hugging Face",
    url: "https://huggingface.co/learn",
    trackKeys: ["ai_ml"],
    tags: ["ml", "nlp", "documentation", "projects"],
    resourceType: "course",
    providerType: "course",
    level: "intermediate",
    weight: 9,
  },
  {
    key: "fastai",
    title: "Practical Deep Learning for Coders",
    provider: "fast.ai",
    url: "https://course.fast.ai/",
    trackKeys: ["ai_ml"],
    tags: ["ml", "projects", "practice"],
    resourceType: "course",
    providerType: "course",
    level: "intermediate",
    weight: 9,
  },
  {
    key: "pytorch",
    title: "PyTorch Tutorials",
    provider: "PyTorch",
    url: "https://pytorch.org/tutorials/",
    trackKeys: ["ai_ml"],
    tags: ["ml", "documentation", "practice"],
    resourceType: "documentation",
    providerType: "docs",
    level: "intermediate",
    weight: 8,
  },
  {
    key: "tableau_learning",
    title: "Tableau Training",
    provider: "Tableau",
    url: "https://www.tableau.com/learn/training",
    trackKeys: ["data_analytics"],
    tags: ["analytics", "visualization"],
    resourceType: "course",
    providerType: "course",
    level: "beginner",
    weight: 8,
  },
  {
    key: "sqlbolt",
    title: "SQLBolt",
    provider: "SQLBolt",
    url: "https://sqlbolt.com/",
    trackKeys: ["data_analytics", "software_engineering"],
    tags: ["sql", "practice", "foundations"],
    resourceType: "practice",
    providerType: "practice",
    level: "beginner",
    weight: 8,
  },
  {
    key: "pandas_docs",
    title: "Pandas User Guide",
    provider: "pandas",
    url: "https://pandas.pydata.org/docs/user_guide/index.html",
    trackKeys: ["data_analytics", "bio_life_sciences"],
    tags: ["data", "documentation", "practice"],
    resourceType: "documentation",
    providerType: "docs",
    level: "intermediate",
    weight: 7,
  },
  {
    key: "tryhackme",
    title: "TryHackMe",
    provider: "TryHackMe",
    url: "https://tryhackme.com/",
    trackKeys: ["cybersecurity_networking"],
    tags: ["cybersecurity", "hands_on_labs", "practice"],
    resourceType: "practice",
    providerType: "practice",
    level: "beginner",
    weight: 10,
  },
  {
    key: "cisco_skills",
    title: "Cisco Skills for All",
    provider: "Cisco",
    url: "https://www.netacad.com/courses/all-courses",
    trackKeys: ["cybersecurity_networking"],
    tags: ["networking", "cybersecurity", "foundations"],
    resourceType: "course",
    providerType: "course",
    level: "beginner",
    weight: 8,
  },
  {
    key: "owasp",
    title: "OWASP Web Security Testing Guide",
    provider: "OWASP",
    url: "https://owasp.org/www-project-web-security-testing-guide/",
    trackKeys: ["cybersecurity_networking"],
    tags: ["cybersecurity", "documentation", "web"],
    resourceType: "documentation",
    providerType: "docs",
    level: "intermediate",
    weight: 8,
  },
  {
    key: "arduino_docs",
    title: "Arduino Documentation",
    provider: "Arduino",
    url: "https://docs.arduino.cc/",
    trackKeys: ["hardware_embedded"],
    tags: ["hardware", "embedded", "documentation", "projects"],
    resourceType: "documentation",
    providerType: "docs",
    level: "beginner",
    weight: 9,
  },
  {
    key: "raspberry_pi",
    title: "Raspberry Pi Documentation",
    provider: "Raspberry Pi",
    url: "https://www.raspberrypi.com/documentation/",
    trackKeys: ["hardware_embedded"],
    tags: ["hardware", "embedded", "projects", "practice"],
    resourceType: "documentation",
    providerType: "docs",
    level: "beginner",
    weight: 8,
  },
  {
    key: "platformio",
    title: "PlatformIO Docs",
    provider: "PlatformIO",
    url: "https://docs.platformio.org/",
    trackKeys: ["hardware_embedded"],
    tags: ["hardware", "embedded", "tooling", "documentation"],
    resourceType: "documentation",
    providerType: "docs",
    level: "intermediate",
    weight: 7,
  },
  {
    key: "figma_learn",
    title: "Figma Learn",
    provider: "Figma",
    url: "https://help.figma.com/hc/en-us/categories/360002051613",
    trackKeys: ["web_product", "design_creative_media"],
    tags: ["ui_ux", "design", "tooling", "portfolio"],
    resourceType: "documentation",
    providerType: "docs",
    level: "beginner",
    weight: 8,
  },
  {
    key: "adobe_create",
    title: "Adobe Creative Cloud Tutorials",
    provider: "Adobe",
    url: "https://creativecloud.adobe.com/learn",
    trackKeys: ["design_creative_media"],
    tags: ["design", "creative", "projects", "tooling"],
    resourceType: "course",
    providerType: "course",
    level: "beginner",
    weight: 8,
  },
  {
    key: "blender_docs",
    title: "Blender Manual",
    provider: "Blender",
    url: "https://docs.blender.org/manual/en/latest/",
    trackKeys: ["design_creative_media", "game_interactive_media"],
    tags: ["creative", "tooling", "documentation", "projects"],
    resourceType: "documentation",
    providerType: "docs",
    level: "intermediate",
    weight: 8,
  },
  {
    key: "unity_learn",
    title: "Unity Learn",
    provider: "Unity",
    url: "https://learn.unity.com/",
    trackKeys: ["game_interactive_media"],
    tags: ["game_dev", "projects", "practice"],
    resourceType: "course",
    providerType: "course",
    level: "beginner",
    weight: 9,
  },
  {
    key: "unreal_docs",
    title: "Unreal Engine Documentation",
    provider: "Epic Games",
    url: "https://dev.epicgames.com/documentation/unreal-engine/",
    trackKeys: ["game_interactive_media"],
    tags: ["game_dev", "documentation", "projects"],
    resourceType: "documentation",
    providerType: "docs",
    level: "intermediate",
    weight: 8,
  },
  {
    key: "galaxy_training",
    title: "Galaxy Training Network",
    provider: "Galaxy",
    url: "https://training.galaxyproject.org/",
    trackKeys: ["bio_life_sciences"],
    tags: ["bioinformatics", "research", "practice", "documentation"],
    resourceType: "course",
    providerType: "course",
    level: "beginner",
    weight: 8,
  },
  {
    key: "bioconductor",
    title: "Bioconductor",
    provider: "Bioconductor",
    url: "https://www.bioconductor.org/help/",
    trackKeys: ["bio_life_sciences"],
    tags: ["bioinformatics", "documentation", "research"],
    resourceType: "documentation",
    providerType: "docs",
    level: "intermediate",
    weight: 8,
  },
];

module.exports = { RESOURCE_CATALOG };
